# registration
spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ENC(utxhhZFdfKFSXFhGWKjE7jGvd1wD29aH5CQ4kiimMBs=)
            client-secret: ENC(0CnwqmRdbNTG9MfvKTxH4XQwttngZ0Xz)
            redirect-uri: {baseUrl}/{action}/oauth2/code/{registrationId}
            authorization-grant-type: authorization_code
            scope: ENC(kNRhRm1eACo1Z3ELm/y5McddVnb8QSFsw8vhm+a5WHZr+xY81TSy3l8dmYbaFUWe)
            client-name: Naver
          google:
            client-id: ENC(ptk9fsezWdyHpbqo5G6QhUIOwYrHZ1ykTn2WfHQfhQpUYpvlcxnvjRH0FOaFDxGXHtFLk8b4o/Vc/qENGrWNiBb43MA7wfQj/XDv/SxzFNP9KRFrCHvqFg==)
            client-secret: ENC(LkvnnGXfVS4T/JwqjtQvFE8/Mm4zFvHxigv6NDEotL2mhGj71HztgH0+G871ZudC)
            scope: ENC(cDLETDA3/LDj+QZqaFGQJyNarLH5SMQe)
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response